package com.onlyforchris.store.dal.mapper;

import com.onlyforchris.store.dal.model.Aftersale;
import com.onlyforchris.store.dal.model.AftersaleExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface AftersaleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aftersale
     *
     * @mbg.generated
     */
    long countByExample(AftersaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aftersale
     *
     * @mbg.generated
     */
    int deleteByExample(AftersaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aftersale
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aftersale
     *
     * @mbg.generated
     */
    int insert(Aftersale record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aftersale
     *
     * @mbg.generated
     */
    int insertSelective(Aftersale record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aftersale
     *
     * @mbg.generated
     */
    Aftersale selectOneByExample(AftersaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aftersale
     *
     * @mbg.generated
     */
    Aftersale selectOneByExampleSelective(@Param("example") AftersaleExample example, @Param("selective") Aftersale.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aftersale
     *
     * @mbg.generated
     */
    List<Aftersale> selectByExampleSelective(@Param("example") AftersaleExample example, @Param("selective") Aftersale.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aftersale
     *
     * @mbg.generated
     */
    List<Aftersale> selectByExample(AftersaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aftersale
     *
     * @mbg.generated
     */
    Aftersale selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") Aftersale.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aftersale
     *
     * @mbg.generated
     */
    Aftersale selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aftersale
     *
     * @mbg.generated
     */
    Aftersale selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aftersale
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Aftersale record, @Param("example") AftersaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aftersale
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Aftersale record, @Param("example") AftersaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aftersale
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Aftersale record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aftersale
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Aftersale record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aftersale
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") AftersaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aftersale
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}