package com.onlyforchris.store.dal.mapper;

import org.apache.ibatis.annotations.Param;
import com.onlyforchris.store.dal.model.GrouponRules;
import com.onlyforchris.store.dal.model.GrouponRulesExample;

import java.util.List;

public interface GrouponRulesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupon_rules
     *
     * @mbg.generated
     */
    long countByExample(GrouponRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupon_rules
     *
     * @mbg.generated
     */
    int deleteByExample(GrouponRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupon_rules
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupon_rules
     *
     * @mbg.generated
     */
    int insert(GrouponRules record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupon_rules
     *
     * @mbg.generated
     */
    int insertSelective(GrouponRules record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupon_rules
     *
     * @mbg.generated
     */
    GrouponRules selectOneByExample(GrouponRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupon_rules
     *
     * @mbg.generated
     */
    GrouponRules selectOneByExampleSelective(@Param("example") GrouponRulesExample example, @Param("selective") GrouponRules.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupon_rules
     *
     * @mbg.generated
     */
    List<GrouponRules> selectByExampleSelective(@Param("example") GrouponRulesExample example, @Param("selective") GrouponRules.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupon_rules
     *
     * @mbg.generated
     */
    List<GrouponRules> selectByExample(GrouponRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupon_rules
     *
     * @mbg.generated
     */
    GrouponRules selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") GrouponRules.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupon_rules
     *
     * @mbg.generated
     */
    GrouponRules selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupon_rules
     *
     * @mbg.generated
     */
    GrouponRules selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupon_rules
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") GrouponRules record, @Param("example") GrouponRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupon_rules
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") GrouponRules record, @Param("example") GrouponRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupon_rules
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(GrouponRules record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupon_rules
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GrouponRules record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupon_rules
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") GrouponRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupon_rules
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}