package com.onlyforchris.store.dal.mapper;

import com.onlyforchris.store.dal.model.Groupon;
import com.onlyforchris.store.dal.model.GrouponExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface GrouponMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupon
     *
     * @mbg.generated
     */
    long countByExample(GrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupon
     *
     * @mbg.generated
     */
    int deleteByExample(GrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupon
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupon
     *
     * @mbg.generated
     */
    int insert(Groupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupon
     *
     * @mbg.generated
     */
    int insertSelective(Groupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupon
     *
     * @mbg.generated
     */
    Groupon selectOneByExample(GrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupon
     *
     * @mbg.generated
     */
    Groupon selectOneByExampleSelective(@Param("example") GrouponExample example, @Param("selective") Groupon.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupon
     *
     * @mbg.generated
     */
    List<Groupon> selectByExampleSelective(@Param("example") GrouponExample example, @Param("selective") Groupon.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupon
     *
     * @mbg.generated
     */
    List<Groupon> selectByExample(GrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupon
     *
     * @mbg.generated
     */
    Groupon selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") Groupon.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupon
     *
     * @mbg.generated
     */
    Groupon selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupon
     *
     * @mbg.generated
     */
    Groupon selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupon
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Groupon record, @Param("example") GrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupon
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Groupon record, @Param("example") GrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupon
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Groupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupon
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Groupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupon
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") GrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupon
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}