spring:
  profiles:
    active: dal
  messages:
    encoding: UTF-8

logging:
  level:
    root: ERROR
    org.springframework: ERROR
    org.mybatis: ERROR
    com.onlyforchris.store.dal: DEBUG

mybatis:
  mapper-locations: classpath:/mapper/*.xml