spring:
  profiles:
    active: core, dal
  messages:
    encoding: UTF-8

logging:
  level:
    root: ERROR
    org.springframework: ERROR
    org.mybatis: ERROR
    com.onlyforchris.store.core: DEBUG